services:
  postgresiobenchmarklinux:
    image: ${DOCKER_REGISTRY-}postgresiobenchmarklinux
    build:
      context: .
      dockerfile: PostgresIOBenchmark/Dockerfile
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: benchmarkdb
    volumes:
      - pgdata_benchmark:/var/lib/postgresql/data
    ports:
      - "5437:5432"

volumes:
  pgdata_benchmark:
